apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Release.Name }}
    component: backend
    environment: {{ .Values.global.environment }}
    managed-by: helm
data:
  # Host del Service de PostgreSQL — nombre generado por Bitnami: <release>-postgresql
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
